/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesModuleIdRouteImport } from './routes/modules.$moduleId'
import { Route as AuthenticatedUniversitiesRouteImport } from './routes/_authenticated/universities'
import { Route as AuthenticatedUndergradRouteImport } from './routes/_authenticated/undergrad'
import { Route as AuthenticatedTestsRouteImport } from './routes/_authenticated/tests'
import { Route as AuthenticatedSopRouteImport } from './routes/_authenticated/sop'
import { Route as AuthenticatedScholarshipsRouteImport } from './routes/_authenticated/scholarships'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedPublicationsRouteImport } from './routes/_authenticated/publications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPhdRouteImport } from './routes/_authenticated/phd'
import { Route as AuthenticatedPathRouteImport } from './routes/_authenticated/path'
import { Route as AuthenticatedMastersRouteImport } from './routes/_authenticated/masters'
import { Route as AuthenticatedEcaRouteImport } from './routes/_authenticated/eca'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCvRouteImport } from './routes/_authenticated/cv'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedUniversitiesIdRouteImport } from './routes/_authenticated/universities.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUniversitiesRoute =
  AuthenticatedUniversitiesRouteImport.update({
    id: '/universities',
    path: '/universities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUndergradRoute = AuthenticatedUndergradRouteImport.update({
  id: '/undergrad',
  path: '/undergrad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsRoute = AuthenticatedTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSopRoute = AuthenticatedSopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScholarshipsRoute =
  AuthenticatedScholarshipsRouteImport.update({
    id: '/scholarships',
    path: '/scholarships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPublicationsRoute =
  AuthenticatedPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhdRoute = AuthenticatedPhdRouteImport.update({
  id: '/phd',
  path: '/phd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPathRoute = AuthenticatedPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMastersRoute = AuthenticatedMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcaRoute = AuthenticatedEcaRouteImport.update({
  id: '/eca',
  path: '/eca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvRoute = AuthenticatedCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUniversitiesIdRoute =
  AuthenticatedUniversitiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedUniversitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/cv': typeof AuthenticatedCvRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/eca': typeof AuthenticatedEcaRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/path': typeof AuthenticatedPathRoute
  '/phd': typeof AuthenticatedPhdRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/publications': typeof AuthenticatedPublicationsRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/research': typeof AuthenticatedResearchRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/scholarships': typeof AuthenticatedScholarshipsRoute
  '/sop': typeof AuthenticatedSopRoute
  '/tests': typeof AuthenticatedTestsRoute
  '/undergrad': typeof AuthenticatedUndergradRoute
  '/universities': typeof AuthenticatedUniversitiesRouteWithChildren
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/universities/$id': typeof AuthenticatedUniversitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/cv': typeof AuthenticatedCvRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/eca': typeof AuthenticatedEcaRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/path': typeof AuthenticatedPathRoute
  '/phd': typeof AuthenticatedPhdRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/publications': typeof AuthenticatedPublicationsRoute
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/research': typeof AuthenticatedResearchRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/scholarships': typeof AuthenticatedScholarshipsRoute
  '/sop': typeof AuthenticatedSopRoute
  '/tests': typeof AuthenticatedTestsRoute
  '/undergrad': typeof AuthenticatedUndergradRoute
  '/universities': typeof AuthenticatedUniversitiesRouteWithChildren
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/universities/$id': typeof AuthenticatedUniversitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/cv': typeof AuthenticatedCvRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/eca': typeof AuthenticatedEcaRoute
  '/_authenticated/masters': typeof AuthenticatedMastersRoute
  '/_authenticated/path': typeof AuthenticatedPathRoute
  '/_authenticated/phd': typeof AuthenticatedPhdRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/publications': typeof AuthenticatedPublicationsRoute
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/scholarships': typeof AuthenticatedScholarshipsRoute
  '/_authenticated/sop': typeof AuthenticatedSopRoute
  '/_authenticated/tests': typeof AuthenticatedTestsRoute
  '/_authenticated/undergrad': typeof AuthenticatedUndergradRoute
  '/_authenticated/universities': typeof AuthenticatedUniversitiesRouteWithChildren
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/_authenticated/universities/$id': typeof AuthenticatedUniversitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/applications'
    | '/cv'
    | '/dashboard'
    | '/documents'
    | '/eca'
    | '/masters'
    | '/path'
    | '/phd'
    | '/profile'
    | '/publications'
    | '/recommendations'
    | '/research'
    | '/roadmap'
    | '/scholarships'
    | '/sop'
    | '/tests'
    | '/undergrad'
    | '/universities'
    | '/modules/$moduleId'
    | '/universities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/applications'
    | '/cv'
    | '/dashboard'
    | '/documents'
    | '/eca'
    | '/masters'
    | '/path'
    | '/phd'
    | '/profile'
    | '/publications'
    | '/recommendations'
    | '/research'
    | '/roadmap'
    | '/scholarships'
    | '/sop'
    | '/tests'
    | '/undergrad'
    | '/universities'
    | '/modules/$moduleId'
    | '/universities/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/applications'
    | '/_authenticated/cv'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/eca'
    | '/_authenticated/masters'
    | '/_authenticated/path'
    | '/_authenticated/phd'
    | '/_authenticated/profile'
    | '/_authenticated/publications'
    | '/_authenticated/recommendations'
    | '/_authenticated/research'
    | '/_authenticated/roadmap'
    | '/_authenticated/scholarships'
    | '/_authenticated/sop'
    | '/_authenticated/tests'
    | '/_authenticated/undergrad'
    | '/_authenticated/universities'
    | '/modules/$moduleId'
    | '/_authenticated/universities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ModulesModuleIdRoute: typeof ModulesModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/universities': {
      id: '/_authenticated/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof AuthenticatedUniversitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/undergrad': {
      id: '/_authenticated/undergrad'
      path: '/undergrad'
      fullPath: '/undergrad'
      preLoaderRoute: typeof AuthenticatedUndergradRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests': {
      id: '/_authenticated/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AuthenticatedTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sop': {
      id: '/_authenticated/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof AuthenticatedSopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scholarships': {
      id: '/_authenticated/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof AuthenticatedScholarshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publications': {
      id: '/_authenticated/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof AuthenticatedPublicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/phd': {
      id: '/_authenticated/phd'
      path: '/phd'
      fullPath: '/phd'
      preLoaderRoute: typeof AuthenticatedPhdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/path': {
      id: '/_authenticated/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof AuthenticatedPathRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters': {
      id: '/_authenticated/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AuthenticatedMastersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eca': {
      id: '/_authenticated/eca'
      path: '/eca'
      fullPath: '/eca'
      preLoaderRoute: typeof AuthenticatedEcaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv': {
      id: '/_authenticated/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof AuthenticatedCvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/universities/$id': {
      id: '/_authenticated/universities/$id'
      path: '/$id'
      fullPath: '/universities/$id'
      preLoaderRoute: typeof AuthenticatedUniversitiesIdRouteImport
      parentRoute: typeof AuthenticatedUniversitiesRoute
    }
  }
}

interface AuthenticatedUniversitiesRouteChildren {
  AuthenticatedUniversitiesIdRoute: typeof AuthenticatedUniversitiesIdRoute
}

const AuthenticatedUniversitiesRouteChildren: AuthenticatedUniversitiesRouteChildren =
  {
    AuthenticatedUniversitiesIdRoute: AuthenticatedUniversitiesIdRoute,
  }

const AuthenticatedUniversitiesRouteWithChildren =
  AuthenticatedUniversitiesRoute._addFileChildren(
    AuthenticatedUniversitiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedCvRoute: typeof AuthenticatedCvRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEcaRoute: typeof AuthenticatedEcaRoute
  AuthenticatedMastersRoute: typeof AuthenticatedMastersRoute
  AuthenticatedPathRoute: typeof AuthenticatedPathRoute
  AuthenticatedPhdRoute: typeof AuthenticatedPhdRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPublicationsRoute: typeof AuthenticatedPublicationsRoute
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedScholarshipsRoute: typeof AuthenticatedScholarshipsRoute
  AuthenticatedSopRoute: typeof AuthenticatedSopRoute
  AuthenticatedTestsRoute: typeof AuthenticatedTestsRoute
  AuthenticatedUndergradRoute: typeof AuthenticatedUndergradRoute
  AuthenticatedUniversitiesRoute: typeof AuthenticatedUniversitiesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedCvRoute: AuthenticatedCvRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEcaRoute: AuthenticatedEcaRoute,
  AuthenticatedMastersRoute: AuthenticatedMastersRoute,
  AuthenticatedPathRoute: AuthenticatedPathRoute,
  AuthenticatedPhdRoute: AuthenticatedPhdRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPublicationsRoute: AuthenticatedPublicationsRoute,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedScholarshipsRoute: AuthenticatedScholarshipsRoute,
  AuthenticatedSopRoute: AuthenticatedSopRoute,
  AuthenticatedTestsRoute: AuthenticatedTestsRoute,
  AuthenticatedUndergradRoute: AuthenticatedUndergradRoute,
  AuthenticatedUniversitiesRoute: AuthenticatedUniversitiesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ModulesModuleIdRoute: ModulesModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
