
ALTER TABLE public.universities
  ADD COLUMN IF NOT EXISTS region text,
  ADD COLUMN IF NOT EXISTS continent text,
  ADD COLUMN IF NOT EXISTS campus_type text,
  ADD COLUMN IF NOT EXISTS faculties text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS tuition_min_usd integer,
  ADD COLUMN IF NOT EXISTS tuition_max_usd integer,
  ADD COLUMN IF NOT EXISTS living_cost_usd integer,
  ADD COLUMN IF NOT EXISTS housing_cost_usd integer,
  ADD COLUMN IF NOT EXISTS currency text,
  ADD COLUMN IF NOT EXISTS avg_gpa numeric,
  ADD COLUMN IF NOT EXISTS ielts_min numeric,
  ADD COLUMN IF NOT EXISTS toefl_min integer,
  ADD COLUMN IF NOT EXISTS det_min integer,
  ADD COLUMN IF NOT EXISTS gre_required boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS gmat_required boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS application_deadline text,
  ADD COLUMN IF NOT EXISTS required_documents text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS admission_notes text,
  ADD COLUMN IF NOT EXISTS visa_info text,
  ADD COLUMN IF NOT EXISTS work_during_study text,
  ADD COLUMN IF NOT EXISTS post_study_work text,
  ADD COLUMN IF NOT EXISTS pr_pathway text,
  ADD COLUMN IF NOT EXISTS scholarships_info text,
  ADD COLUMN IF NOT EXISTS research_areas text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS exchange_partners text,
  ADD COLUMN IF NOT EXISTS employability_rank integer,
  ADD COLUMN IF NOT EXISTS notable_alumni text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS image_url text,
  ADD COLUMN IF NOT EXISTS latitude numeric,
  ADD COLUMN IF NOT EXISTS longitude numeric,
  ADD COLUMN IF NOT EXISTS established_year integer,
  ADD COLUMN IF NOT EXISTS student_count integer,
  ADD COLUMN IF NOT EXISTS intl_ratio numeric,
  ADD COLUMN IF NOT EXISTS qs_rank integer,
  ADD COLUMN IF NOT EXISTS the_rank integer,
  ADD COLUMN IF NOT EXISTS arwu_rank integer;

CREATE INDEX IF NOT EXISTS universities_country_idx ON public.universities(country);
CREATE INDEX IF NOT EXISTS universities_world_rank_idx ON public.universities(world_rank);
