ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phd_pathway text;

CREATE TABLE IF NOT EXISTS public.phd_positions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  university text NOT NULL,
  country text,
  department text,
  research_group text,
  supervisor text,
  supervisor_profile text,
  research_area text,
  keywords text[] DEFAULT '{}'::text[],
  degree_type text,
  funding_type text,
  fully_funded boolean NOT NULL DEFAULT false,
  industry_sponsored boolean NOT NULL DEFAULT false,
  stipend_monthly text,
  tuition_covered boolean DEFAULT false,
  health_insurance boolean DEFAULT false,
  research_budget text,
  duration_years numeric,
  required_gpa numeric,
  language_requirement text,
  research_experience text,
  required_documents text[] DEFAULT '{}'::text[],
  interview_process text,
  description text,
  deadline date,
  link text,
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.phd_positions TO anon;
GRANT SELECT ON public.phd_positions TO authenticated;
GRANT ALL ON public.phd_positions TO service_role;

ALTER TABLE public.phd_positions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "phd positions public read" ON public.phd_positions;
CREATE POLICY "phd positions public read" ON public.phd_positions FOR SELECT TO anon, authenticated USING (true);

INSERT INTO public.phd_positions (title, university, country, department, research_group, supervisor, research_area, keywords, degree_type, funding_type, fully_funded, industry_sponsored, stipend_monthly, tuition_covered, health_insurance, research_budget, duration_years, required_gpa, language_requirement, research_experience, required_documents, interview_process, description, deadline, link) VALUES
('PhD in Machine Learning', 'Massachusetts Institute of Technology', 'USA', 'EECS', 'CSAIL Learning & Intelligent Systems', 'Prof. Leslie Kaelbling', 'Machine Learning', ARRAY['machine learning','robotics','planning'], 'Direct PhD', 'University Funding', true, false, 'USD 4,000', true, true, 'USD 5,000/yr travel', 5, 3.7, 'TOEFL 100 / IELTS 7.0', 'Prior research or publications preferred', ARRAY['Transcript','Statement of Purpose','CV','3 Recommendation letters'], 'Two faculty interviews + research discussion', 'Doctoral research on learning-based robot decision making and planning under uncertainty.', '2026-12-15', 'https://gradapply.mit.edu/eecs'),
('PhD in Artificial Intelligence', 'Stanford University', 'USA', 'Computer Science', 'Stanford AI Lab', 'Prof. Chelsea Finn', 'AI / Robot Learning', ARRAY['deep learning','meta-learning','robotics'], 'Direct PhD', 'University Funding', true, false, 'USD 4,200', true, true, 'Conference travel covered', 5, 3.8, 'TOEFL 100', 'Strong research record expected', ARRAY['Transcript','SOP','CV','3 Recommendation letters'], 'Faculty interviews (Jan–Feb)', 'Research on robot learning, foundation models and generalization.', '2026-12-01', 'https://cs.stanford.edu/admissions'),
('PhD in Quantum Materials', 'University of Cambridge', 'UK', 'Physics (Cavendish)', 'Quantum Matter Group', 'Prof. Suchitra Sebastian', 'Condensed Matter Physics', ARRAY['quantum materials','superconductivity'], 'Direct PhD', 'Government Fellowship', true, false, 'GBP 1,900', true, true, 'GBP 3,000/yr consumables', 4, 3.6, 'IELTS 7.0', 'MSc-level lab experience', ARRAY['Transcript','Research proposal','CV','2 References'], 'Panel interview', 'Experimental study of unconventional superconductors under extreme conditions.', '2026-12-03', 'https://www.postgraduate.study.cam.ac.uk'),
('DPhil in Machine Learning', 'University of Oxford', 'UK', 'Computer Science', 'OATML', 'Prof. Yarin Gal', 'Probabilistic ML', ARRAY['bayesian deep learning','uncertainty'], 'Direct PhD', 'University Funding', true, false, 'GBP 1,850', true, true, 'Included', 4, 3.7, 'IELTS 7.5', 'Publications advantageous', ARRAY['Transcript','Research proposal','CV','3 References'], 'Two-stage interview', 'Research in uncertainty quantification and reliable deep learning.', '2026-12-05', 'https://www.ox.ac.uk/admissions/graduate'),
('PhD in Climate Science', 'ETH Zurich', 'Switzerland', 'Environmental Systems Science', 'Institute for Atmospheric and Climate Science', 'Prof. Reto Knutti', 'Climate Modelling', ARRAY['climate','earth system models'], 'Funded PhD', 'University Funding', true, false, 'CHF 4,800', true, true, 'CHF 5,000/yr', 4, 3.5, 'English C1', 'Programming + modelling experience', ARRAY['CV','Motivation letter','Transcript','2 References'], 'Interview with group', 'Doctoral position on climate model uncertainty and regional projections.', '2027-01-31', 'https://ethz.ch/en/doctorate'),
('PhD in Robotics', 'Technical University of Munich', 'Germany', 'Informatics', 'Robotics & AI Group', 'Prof. Sami Haddadin', 'Robotics', ARRAY['human-robot interaction','control'], 'Funded PhD', 'Government Fellowship', true, false, 'EUR 3,200', true, true, 'EUR 4,000/yr', 4, 3.4, 'English B2/C1', 'Hands-on robotics projects', ARRAY['CV','Transcript','Motivation letter','References'], 'Technical interview + lab visit', 'Research on safe physical human-robot interaction and tactile control.', '2027-02-28', 'https://www.tum.de/en/studies/phd'),
('Industrial PhD in Battery Materials', 'KTH Royal Institute of Technology', 'Sweden', 'Chemical Engineering', 'Applied Electrochemistry', 'Prof. Rakel Lindbergh', 'Energy Materials', ARRAY['batteries','electrochemistry'], 'Industry PhD', 'Industrial Funding', true, true, 'SEK 34,000', true, true, 'Company funded', 5, 3.3, 'IELTS 6.5', 'Lab experience in electrochemistry', ARRAY['CV','Cover letter','Transcript','References'], 'Company + academic interview', 'Industry-sponsored doctorate on next-generation lithium battery interfaces.', '2027-03-15', 'https://www.kth.se/en/studies/phd'),
('PhD in Computational Biology', 'University of Toronto', 'Canada', 'Molecular Genetics', 'Donnelly Centre', 'Prof. Quaid Morris', 'Computational Biology', ARRAY['genomics','bayesian methods'], 'Direct PhD', 'University Funding', true, false, 'CAD 3,100', true, true, 'CAD 2,000/yr', 5, 3.5, 'TOEFL 93 / IELTS 7.0', 'Bioinformatics coursework or research', ARRAY['Transcript','SOP','CV','2 References'], 'Supervisor interview', 'Probabilistic models of cancer evolution from sequencing data.', '2026-12-10', 'https://www.utoronto.ca/graduate'),
('PhD in Renewable Energy Systems', 'University of Melbourne', 'Australia', 'Electrical Engineering', 'Power & Energy Group', 'Prof. Pierluigi Mancarella', 'Energy Systems', ARRAY['power systems','grid integration'], 'Funded PhD', 'University Funding', true, false, 'AUD 3,000', true, true, 'AUD 5,000 total', 3.5, 3.4, 'IELTS 6.5', 'Engineering research project', ARRAY['CV','Research proposal','Transcript','2 References'], 'Online interview', 'Doctoral research on resilient renewable-dominated power grids.', '2026-10-31', 'https://study.unimelb.edu.au/find/courses/graduate-research'),
('PhD in Neuroscience', 'University College London', 'UK', 'Neuroscience', 'Gatsby Computational Neuroscience Unit', 'Prof. Peter Latham', 'Computational Neuroscience', ARRAY['neural coding','theory'], 'Direct PhD', 'Foundation Grant', true, false, 'GBP 2,100', true, true, 'Included', 4, 3.6, 'IELTS 7.0', 'Strong maths background', ARRAY['Transcript','CV','Research statement','3 References'], 'Interview week in London', 'Theoretical work on inference and learning in neural circuits.', '2026-11-30', 'https://www.ucl.ac.uk/prospective-students/graduate'),
('PhD in Materials Science (MEXT)', 'University of Tokyo', 'Japan', 'Materials Engineering', 'Advanced Materials Lab', 'Prof. Hideo Hosono', 'Materials Science', ARRAY['semiconductors','thin films'], 'Funded PhD', 'Government Fellowship', true, false, 'JPY 145,000', true, true, 'Lab funded', 3, 3.3, 'English or Japanese N2', 'MSc thesis in materials', ARRAY['Research plan','Transcript','CV','2 References'], 'Supervisor interview (online)', 'MEXT-funded doctorate on oxide semiconductors for electronics.', '2027-05-31', 'https://www.u-tokyo.ac.jp/en/prospective-students'),
('PhD in AI for Healthcare', 'National University of Singapore', 'Singapore', 'Computer Science', 'NUS Medical AI Lab', 'Prof. Ooi Beng Chin', 'Medical AI', ARRAY['clinical AI','data systems'], 'Direct PhD', 'University Funding', true, false, 'SGD 2,700', true, true, 'SGD 4,000/yr', 4, 3.5, 'TOEFL 92', 'Research or industry ML experience', ARRAY['Transcript','SOP','CV','2 References'], 'Technical + research interview', 'Doctoral research on trustworthy clinical decision support systems.', '2026-12-15', 'https://www.comp.nus.edu.sg/programmes/pg/phd'),
('Cotutelle PhD in Photonics', 'KU Leuven', 'Belgium', 'Electrical Engineering', 'Photonics Research Group', 'Prof. Roel Baets', 'Photonics', ARRAY['silicon photonics','biosensing'], 'Cotutelle (Dual PhD)', 'International Fellowship', true, false, 'EUR 2,600', true, true, 'EUR 6,000/yr', 4, 3.4, 'IELTS 7.0', 'Cleanroom or optics experience', ARRAY['CV','Motivation letter','Transcript','References'], 'Joint interview with partner university', 'Dual-degree doctorate on integrated photonic biosensors.', '2027-01-15', 'https://www.kuleuven.be/english/research/phd'),
('PhD in Public Health', 'Karolinska Institutet', 'Sweden', 'Global Public Health', 'Health Systems and Policy', 'Prof. Tobias Alfven', 'Public Health', ARRAY['epidemiology','global health'], 'Funded PhD', 'Government Fellowship', true, false, 'SEK 33,000', true, true, 'Project funded', 4, 3.3, 'IELTS 6.5', 'Field or epidemiological research', ARRAY['CV','Cover letter','Transcript','References'], 'Panel interview', 'Doctoral research on health system strengthening in LMICs.', '2027-02-15', 'https://ki.se/en/education/doctoral-education'),
('PhD in Economics', 'London School of Economics', 'UK', 'Economics', 'Development Economics', 'Prof. Oriana Bandiera', 'Development Economics', ARRAY['field experiments','labour'], 'Direct PhD', 'University Funding', true, false, 'GBP 2,000', true, true, 'Fieldwork grant', 5, 3.7, 'IELTS 7.0', 'RA experience valued', ARRAY['Transcript','GRE','SOP','3 References'], 'Interview + research talk', 'PhD in development and labour economics with field experiments.', '2027-01-14', 'https://www.lse.ac.uk/study-at-lse/Graduate'),
('PhD in Quantum Computing', 'Delft University of Technology', 'Netherlands', 'QuTech', 'Quantum Internet Division', 'Prof. Stephanie Wehner', 'Quantum Information', ARRAY['quantum networks','protocols'], 'Funded PhD', 'Government Fellowship', true, false, 'EUR 2,900', true, true, 'EUR 5,000/yr', 4, 3.5, 'IELTS 7.0', 'Quantum information coursework', ARRAY['CV','Motivation letter','Transcript','2 References'], 'Two interviews', 'Doctoral research on quantum network protocols and stacks.', '2027-03-01', 'https://www.tudelft.nl/en/education/programmes/phd'),
('PhD in Environmental Engineering', 'University of British Columbia', 'Canada', 'Civil Engineering', 'Water Research Group', 'Prof. Pierre Berube', 'Water Treatment', ARRAY['membranes','water reuse'], 'Funded PhD', 'Research Grant', true, false, 'CAD 2,600', true, true, 'CAD 3,000/yr', 4, 3.3, 'IELTS 6.5', 'Lab-based MSc preferred', ARRAY['CV','Transcript','SOP','2 References'], 'Supervisor interview', 'Doctoral study of low-energy membrane processes for water reuse.', '2027-01-15', 'https://www.grad.ubc.ca'),
('Integrated PhD in Life Sciences', 'EMBL Heidelberg', 'Germany', 'Structural Biology', 'EMBL International PhD Programme', 'Various group leaders', 'Structural Biology', ARRAY['cryo-EM','proteins'], 'Integrated PhD', 'International Fellowship', true, false, 'EUR 2,300', true, true, 'Fully covered', 4, 3.5, 'English proficiency', 'Wet-lab research experience', ARRAY['CV','Motivation letter','Transcript','2 References'], 'EMBL interview week', 'Integrated doctoral programme with rotations across EMBL units.', '2027-01-10', 'https://www.embl.org/about/info/phd-programme'),
('PhD in Aerospace Engineering', 'Caltech', 'USA', 'GALCIT', 'Aerospace Lab', 'Prof. Beverley McKeon', 'Fluid Mechanics', ARRAY['turbulence','flow control'], 'Direct PhD', 'University Funding', true, false, 'USD 3,600', true, true, 'Included', 5, 3.7, 'TOEFL 100', 'Experimental or numerical research', ARRAY['Transcript','SOP','CV','3 References'], 'Faculty interviews', 'Doctoral research on turbulent boundary layers and flow control.', '2026-12-15', 'https://www.gradoffice.caltech.edu'),
('PhD in Social Policy', 'University of Amsterdam', 'Netherlands', 'Social Sciences', 'Institute for Societal Resilience', 'Prof. Marieke van Houte', 'Migration Studies', ARRAY['migration','policy'], 'Funded PhD', 'Government Fellowship', true, false, 'EUR 2,800', true, true, 'EUR 3,000/yr', 4, 3.2, 'IELTS 7.0', 'Qualitative fieldwork experience', ARRAY['CV','Research proposal','Transcript','References'], 'Interview + writing sample', 'Doctoral research on migration governance in Europe.', '2027-02-01', 'https://www.uva.nl/en/research/phd'),
('PhD in Agricultural Science', 'Wageningen University', 'Netherlands', 'Plant Sciences', 'Crop Systems Analysis', 'Prof. Niels Anten', 'Agronomy', ARRAY['crop modelling','sustainability'], 'Funded PhD', 'Research Grant', true, false, 'EUR 2,770', true, true, 'Field trials funded', 4, 3.2, 'IELTS 6.5', 'Field or modelling experience', ARRAY['CV','Motivation letter','Transcript','References'], 'Online interview', 'Doctorate on climate-resilient cropping systems.', '2027-03-31', 'https://www.wur.nl/en/education-programmes/phd-programme.htm'),
('Professional Doctorate in Education (EdD)', 'University of Sydney', 'Australia', 'Education', 'Education Futures', 'Prof. Jane Hunter', 'Education', ARRAY['pedagogy','policy'], 'Professional Doctorate', 'University Funding', false, false, 'Part scholarship', false, false, 'N/A', 4, 3.0, 'IELTS 7.0', '3+ years professional experience', ARRAY['CV','Research proposal','Transcript','References'], 'Interview', 'Practice-based doctorate for experienced educators and leaders.', '2027-04-30', 'https://www.sydney.edu.au/study/study-options/research-degrees.html'),
('PhD in Cybersecurity', 'EPFL', 'Switzerland', 'Computer Science', 'Security and Privacy Lab', 'Prof. Carmela Troncoso', 'Privacy Engineering', ARRAY['privacy','security'], 'Funded PhD', 'University Funding', true, false, 'CHF 4,700', true, true, 'CHF 5,000/yr', 4, 3.5, 'English C1', 'Security research or CTF/engineering background', ARRAY['CV','Transcript','Motivation letter','3 References'], 'EDIC interview', 'Doctoral research on privacy-preserving systems at scale.', '2027-01-15', 'https://www.epfl.ch/education/phd/'),
('PhD in Materials Chemistry', 'Seoul National University', 'South Korea', 'Chemistry', 'Nanomaterials Lab', 'Prof. Taeghwan Hyeon', 'Nanomaterials', ARRAY['nanoparticles','catalysis'], 'Master''s → PhD', 'Government Fellowship', true, false, 'KRW 2,200,000', true, true, 'Lab funded', 4, 3.4, 'TOEFL 88', 'Synthesis lab experience', ARRAY['CV','Research plan','Transcript','2 References'], 'Lab interview', 'Doctoral research on nanoparticle synthesis for catalysis and bio-imaging.', '2027-05-15', 'https://en.snu.ac.kr/admissions/graduate'),
('PhD in Astronomy', 'Australian National University', 'Australia', 'Astronomy & Astrophysics', 'Mount Stromlo Observatory', 'Prof. Lisa Kewley', 'Astrophysics', ARRAY['galaxy evolution','spectroscopy'], 'Funded PhD', 'Government Fellowship', true, false, 'AUD 3,100', true, true, 'Observing travel funded', 3.5, 3.5, 'IELTS 6.5', 'Astronomy research project', ARRAY['CV','Research proposal','Transcript','2 References'], 'Panel interview', 'Doctoral research on galaxy evolution using integral field spectroscopy.', '2026-10-31', 'https://www.anu.edu.au/study/apply/higher-degree-research'),
('Online PhD in Business Administration', 'University of Liverpool', 'UK', 'Management School', 'Online Doctorate', 'Programme faculty', 'Management', ARRAY['strategy','organisation'], 'Online/Distance PhD', 'Self-Funded', false, false, 'None', false, false, 'N/A', 6, 3.0, 'IELTS 6.5', 'Professional management experience', ARRAY['CV','Research proposal','Transcript','References'], 'Online interview', 'Part-time online doctorate for working professionals.', '2027-06-30', 'https://www.liverpool.ac.uk/study/postgraduate-research/'),
('PhD in Mechanical Engineering (Industry)', 'Chalmers University of Technology', 'Sweden', 'Mechanics and Maritime Sciences', 'Vehicle Dynamics', 'Prof. Bengt Jacobson', 'Vehicle Engineering', ARRAY['autonomous vehicles','dynamics'], 'Industry PhD', 'Industrial Funding', true, true, 'SEK 35,000', true, true, 'Volvo sponsored', 5, 3.3, 'IELTS 6.5', 'Automotive or control experience', ARRAY['CV','Cover letter','Transcript','References'], 'Industry + academic interview', 'Industry-sponsored doctorate on autonomous heavy-vehicle dynamics.', '2027-02-28', 'https://www.chalmers.se/en/education/phd-studies/'),
('PhD in Data Science', 'Tsinghua University', 'China', 'Institute for Interdisciplinary Information Sciences', 'IIIS', 'Prof. Andrew Yao group', 'Theoretical CS / Data Science', ARRAY['algorithms','learning theory'], 'Direct PhD', 'Government Fellowship', true, false, 'CNY 6,000', true, true, 'Lab funded', 4, 3.6, 'English proficiency', 'Olympiad or research background', ARRAY['CV','Transcript','Research statement','2 References'], 'Interview with committee', 'Doctoral research at the interface of algorithms and machine learning.', '2027-03-15', 'https://www.tsinghua.edu.cn/en/Admissions.htm'),
('PhD in Marine Biology', 'University of Cape Town', 'South Africa', 'Biological Sciences', 'Marine Research Institute', 'Prof. Colin Attwood', 'Marine Ecology', ARRAY['fisheries','conservation'], 'Funded PhD', 'NGO Funding', true, false, 'ZAR 22,000', true, false, 'Fieldwork grant', 3, 3.2, 'English proficiency', 'Fieldwork experience', ARRAY['CV','Research proposal','Transcript','2 References'], 'Supervisor interview', 'Doctoral research on sustainable fisheries and marine protected areas.', '2027-04-30', 'https://science.uct.ac.za/'),
('Visiting PhD Researcher — AI Safety', 'University of Montreal (Mila)', 'Canada', 'Computer Science', 'Mila', 'Prof. Yoshua Bengio group', 'AI Safety', ARRAY['alignment','deep learning'], 'Visiting PhD', 'Research Grant', true, false, 'CAD 2,400', false, true, 'Compute provided', 1, 3.5, 'IELTS 6.5', 'Enrolled PhD elsewhere', ARRAY['CV','Home supervisor letter','Research plan'], 'Interview with host', 'Visiting research stay of 6–12 months on AI safety and alignment.', '2027-01-31', 'https://mila.quebec/en/'),
('Postdoctoral Fellowship — Genomics', 'Broad Institute', 'USA', 'Genomics', 'Broad Fellows Program', 'Independent fellowship', 'Genomics', ARRAY['single-cell','genomics'], 'Postdoctoral Preparation', 'International Fellowship', true, false, 'USD 7,000', true, true, 'USD 50,000/yr research budget', 3, 3.5, 'English proficiency', 'PhD completed or near completion', ARRAY['CV','Research proposal','3 References'], 'Symposium + interview', 'Independent postdoctoral fellowship for early-career genomics researchers.', '2027-02-15', 'https://www.broadinstitute.org/broad-fellows-program');